@startuml
!include style.puml

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":AddressBookParser" as AddressBookParser LOGIC_COLOR
participant ":AppointmentFindPatientCommandParser" as AppointmentFindPatientCommandParser LOGIC_COLOR
participant "predicate:SearchPatientFilter" as SearchPatientFilter LOGIC_COLOR
participant "command:AppointmentFindPatientCommand" as AppointmentFindPatientCommand LOGIC_COLOR
participant "result :CommandResult" as CommandResult LOGIC_COLOR
end box

note left of LogicManager: Sequence Diagram \n works for commands \n that  filters the appointment list

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("a-find Jack")
activate LogicManager

LogicManager -> AddressBookParser : parseCommand("a-find Jack")
activate AddressBookParser

create AppointmentFindPatientCommandParser
AddressBookParser -> AppointmentFindPatientCommandParser
activate AppointmentFindPatientCommandParser

AppointmentFindPatientCommandParser --> AddressBookParser
deactivate AppointmentFindPatientCommandParser

AddressBookParser -> AppointmentFindPatientCommandParser : parse("Jack")
activate AppointmentFindPatientCommandParser


create SearchPatientFilter
AppointmentFindPatientCommandParser -> SearchPatientFilter
activate SearchPatientFilter

SearchPatientFilter --> AppointmentFindPatientCommandParser : predicate
deactivate SearchPatientFilter

create AppointmentFindPatientCommand
AppointmentFindPatientCommandParser -> AppointmentFindPatientCommand
activate AppointmentFindPatientCommand

AppointmentFindPatientCommand --> AppointmentFindPatientCommandParser : command
deactivate AppointmentFindPatientCommand

AppointmentFindPatientCommandParser --> AddressBookParser : command
deactivate AppointmentFindPatientCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.
destroy AppointmentFindPatientCommandParser

AddressBookParser --> LogicManager : command
deactivate AddressBookParser

LogicManager -> AppointmentFindPatientCommand : execute()
activate AppointmentFindPatientCommand

AppointmentFindPatientCommand -> Model : updateFilteredAppointmentList(predicate)
activate Model

Model --> AppointmentFindPatientCommand
deactivate Model

create CommandResult
AppointmentFindPatientCommand -> CommandResult
activate CommandResult

CommandResult --> AppointmentFindPatientCommand
deactivate CommandResult

AppointmentFindPatientCommand --> LogicManager : result
deactivate AppointmentFindPatientCommand

[<--LogicManager
deactivate LogicManager
@enduml
