@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000

title After command "delete 5"

package UserHistory <<rectangle>> {
    class State1 as "__uh0:InitialUserHistory__"
    class State2 as "__uh1:NewUserHistory__"
    class State3 as "---uh2:NewUserHistoryTwo---"
}

State1 -[hidden]right-> State2
State2 -[hidden]right-> State3

hide State3

class Pointer as "Current History" #FFA500

Pointer -up-> State2

@end

